Fix Wbitwise-instead-of-logical introduced by clang-r445002
Bug: http://b/215753485

frameworks/base/cmds/incidentd/src/WorkDirectory.cpp:283:38: error: use of bitwise '|' with boolean operands [-Werror,-Wbitwise-instead-of-logical]
            report->set_all_sections(report->all_sections() | args.all());
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                            ||
frameworks/base/cmds/incidentd/src/WorkDirectory.cpp:283:38: note: cast
one or both operands to int to silence this warning

Test: Build with new clang
Change-Id: I8dc614e274c95f8941bf390cb68c60d0328bb31b

Former-commit-id: bf3cc242fca09ed08e3ecb13676654de02238a75