Revert "Delete atoms.proto from statsd"
Revert "Add android bp to proto_logging"

Revert submission 13070789-atomsproto

Reason for revert: Breaks multiple git_master-without-vendor targets

```
out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/build.ninja.d -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja Android.bp
error: frameworks/base/tools/stats_log_api_gen/Android.bp:49:1: "stats-log-api-gen-test" depends on undefined module "libstats_proto_host"
ninja: build stopped: subcommand failed.
```

Reverted Changes:
I184cf8bf8:Add android bp to proto_logging
I36ec354d2:Delete atoms.proto from statsd

Bug: 167962588

Change-Id: Idce97c5cf020473744eb7f96dcfbdc7677c094da

Former-commit-id: 217301c36f7ffd500441cb879a4fa88b770092db