Revert "Enforce that RuntimeShader is only hardware accelerated"
Revert "Add tests to ensure hardware only for RuntimeShader API"

Revert submission 16475336-RuntimeShader_softwareOnly

Reason for revert: Breaking tests as system is dying
Error: Software rendering doesn't support RuntimeShader
Bug: b/211066630

Reverted Changes:
Id0ee4d1f0:Enforce that RuntimeShader is only hardware accele...
Ib4c2e54bd:Add tests to ensure hardware only for RuntimeShade...

Change-Id: Id7bbf2609a06c1cd69f6a457dab44f9478d95742
(cherry picked from commit dc0a51c723080b479fdbc281c2e73c4dc9dc533d [formerly f95fdd94723f2443996477b43897460034c3b7ff])
Merged-In:Id7bbf2609a06c1cd69f6a457dab44f9478d95742

Former-commit-id: 51702d8b9e55a7d7658277b8b3e8ddac76ccf27f