linkToDeath exception cause system server crash
java.util.NoSuchElementException: Death link does not exist

when linkToDeath has remote exception, unlinkToDeath will fail and
throw NoSuchElementException, catch it in AbstractAccessibilityServiceConnection
to avoid system server crash.

Bug: 157580692
Test: manual
Change-Id: I42ce3a458e04539d76555679279d1368e0c61ae0

Former-commit-id: 0c1b92192314a5eba892a6f63958acedcde8ce67