Fixes for Kotlin 2.1
Replace appendln with appendLine to make Kotlin 2.1 happy.

This fixes the following error when compiling with 2.1.10:

```
error: 'fun Appendable.appendln(value: CharSequence?): Appendable'
is deprecated. Use appendLine instead.
```

Fix nullability in various usages of
`com.google.common.truth.Subject.Factory`:

- IgnoreableExpect
- TransitionStateSubject
- DpOffsetSubject

Bug: 399463072
Test: m intdef-annotation-processor
Change-Id: I11eadb3e26dd09bfc7b92c07ccad68f56f1ebba2

Former-commit-id: 63c841008072838c91dc2b563e947a04630f78ab