Fixes for Kotlin 2.1
Replace appendln with appendLine to make Kotlin 2.1 happy.

This fixes the following error when compiling with 2.1.10:

```
error: 'fun Appendable.appendln(value: CharSequence?): Appendable'
is deprecated. Use appendLine instead.
```

Fix nullability in various usages of
`com.google.common.truth.Subject.Factory`:

- IgnoreableExpect
- TransitionStateSubject
- DpOffsetSubject

Bug: 399463072
Test: m intdef-annotation-processor
Change-Id: I11eadb3e26dd09bfc7b92c07ccad68f56f1ebba2
(cherry picked from commit 685f4a2a68b9f47797f6dee06a4aeb497dc72e57 [formerly 63c841008072838c91dc2b563e947a04630f78ab])

Former-commit-id: 8053ac01a06359d0385f6dc20e72a6e86088d959