Cancel NotificationTimeout alarms when canceling notification
If alarms with long timeouts are created, there is a risk of a
crash in system_server because of alarm creation limit is reached:

java.lang.IllegalStateException: Maximum limit of concurrent alarms 500
reached for uid: 1000, callingPackage: android

To avoid this cancel alarms if Notifications are canceled.

Suggested-by: Snild Dolkow <snild@sony.com>

Bug: 186456631
Change-Id: I63343b9450fc817ec6a2f46329de346320463c46

Former-commit-id: ebe03fcb4b287e107faea69f653a8761a92e5af1